### ISSUE TITLE
Heartbeat misnomer

### ISSUE THREAD

**Issue by CMajeri** [cloudtrust/go-jobs#2]
A heartbeat is typically a periodic signal to inform other members that the component is still alive.

We shouldn't include progress info in heartbeat messages.

Either make the heartbeat into an actual heatbeat (seems redundant.)
Or change its name to something more appropriate, like UpdateState or similar.

**Comment by braoru** [comment]
I purpose to name it "status" as this message lead to the job status update.... is that ok for you @CMajeri ?

**Comment by CMajeri** [comment]
That seems reasonable.
Closing this.

**Comment by johandroz** [comment]
The name "status" was already taken, so I changed heartbeat to "StepStatus"
